[package]
name = "xtask-assets"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
image.workspace = true
oxipng.workspace = true
serde.workspace = true
serde_json.workspace = true
